# Generated by Django 4.2.6 on 2024-02-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sku', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated', models.IntegerField(default=0)),
                ('alloc_build', models.IntegerField(default=0)),
                ('alloc_sales', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('incoming', models.IntegerField(default=0)),
                ('build_order', models.IntegerField(default=0)),
                ('net_stock', models.IntegerField(default=0)),
                ('can_build', models.BooleanField(default=False)),
                ('instock', models.IntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='TagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.stock')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.tags')),
            ],
            options={
                'unique_together': {('tag', 'sku')},
            },
        ),
    ]
